name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2
        with:
            path: |
                ~/.sonar
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Run Codescan On Push
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@t27
        with:
          organization: murali67112
          projectKey: my-test-pipeline-1
          codeScanUrl: https://test.codescan.io/
          login: ${{ secrets.codescan_token }}
          generateSarifFile: true
          failOnRedQualityGate: true
      - name: Run Codescan On PR
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@t27
        with:
          organization: murali67112
          projectKey: my-test-pipeline-1
          codeScanUrl: https://test.codescan.io/
          login: ${{ secrets.codescan_token }}
          generateSarifFile: true
          failOnRedQualityGate: true
          args: |
            sonar.pullrequest.branch=${{github.head_ref}}
            sonar.pullrequest.base=${{github.base_ref}}
            sonar.pullrequest.key=${{github.event.number}}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codescan.sarif
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: codescan.sarif
          path: codescan.sarif 
